/* 
Nikitha Nallure
*/

CREATE TABLE STATE (
StateID CHAR(2) NOT NULL,
StateName VARCHAR(25) NOT NULL,
PropNative NUMBER(5,4) NOT NULL,
CONSTRAINT STATE_PK PRIMARY KEY (StateID)
);




CREATE TABLE COLLEGE (
CollegeID CHAR(6) NOT NULL,
CollegeName VARCHAR(80) NOT NULL,
CollegeType VARCHAR(7) NOT NULL,
Students NUMBER(4,0) NOT NULL,
StateID CHAR(2) NOT NULL,
CONSTRAINT COLLEGE_PK PRIMARY KEY (CollegeID),
CONSTRAINT COLLEGE_FK FOREIGN KEY (StateID) 
REFERENCES STATE (StateID)
);




CREATE TABLE DEGREE (
CollegeID CHAR(6) NOT NULL,
DegreeName VARCHAR(9) NOT NULL,
CONSTRAINT DEGREE_PK PRIMARY KEY (CollegeID, DegreeName),
CONSTRAINT DEGREE_FK FOREIGN KEY (CollegeID)         
REFERENCES COLLEGE (CollegeID) 
);




CREATE TABLE PRESIDENT (
CollegeID CHAR(6) NOT NULL,
PresidentID CHAR(9) NOT NULL,
Title CHAR(3) NULL,
FirstName VARCHAR(10) NOT NULL,
LastName VARCHAR(15) NOT NULL,
CONSTRAINT PRESIDENT_PK PRIMARY KEY (PresidentID),      
CONSTRAINT PRESIDENT_FK FOREIGN KEY (CollegeID)          
REFERENCES COLLEGE (CollegeID)
);